### ISSUE TITLE
Add a separate contribution file to docs

### ISSUE THREAD

**Issue by mish24** [systers/macc#102]
I was thinking that while installation guide is already in a steady process to get updated, we might also add a separate 'Contribution' file explaining and guiding the people for the following:
1. Adding remote and upstream
2. Git branches and rebasing
3. Squashing commits and force pushing the changes.

@Neetuj @medhach I would like to send a PR for this. Can I go ahead ? :)

**Comment by medhach** [comment]
I think its a great idea! You could add something like this - https://github.com/systers/powerup-android#contributing-and-developing-a-feature
Make sure you keep it simple for everybody to understand, and I don't think force pushing and rebasing should be included since they are considered a bad coding practice. :)

**Comment by mish24** [comment]
@medhach Sure, I'll avoid those things. I myself faced problems numerous times while force pushing. That's why I thought about adding it :)

**Comment by mish24** [comment]
done in #124
